import express from 'express';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import { z } from 'zod';
import { cert, getApps, initializeApp } from 'firebase-admin/app';
import { getAuth } from 'firebase-admin/auth';
import { FieldValue, getFirestore } from 'firebase-admin/firestore';

const adminEmail = (process.env.ADMIN_EMAIL || 'ma7moud01030382018@gmail.com').toLowerCase();
const serviceAccount = process.env.FIREBASE_SERVICE_ACCOUNT_JSON ? JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT_JSON) : null;
if (!getApps().length) initializeApp(serviceAccount ? { credential: cert(serviceAccount) } : undefined);
const store = getFirestore();
const app = express();
app.disable('x-powered-by');
app.use(helmet({ contentSecurityPolicy: false, crossOriginEmbedderPolicy: false }));
app.use(express.json({ limit: '100kb' }));
app.use(rateLimit({ windowMs: 15 * 60_000, limit: 240, standardHeaders: true, legacyHeaders: false }));

const lessonInput = z.object({ id: z.string().regex(/^[a-z0-9-]{3,80}$/), title: z.string().trim().min(3).max(120), module: z.string().trim().min(2).max(80), description: z.string().trim().min(10).max(500), level: z.enum(['تمهيدي', 'متوسط', 'متقدم']), duration: z.number().int().min(1).max(240), published: z.boolean(), questions: z.array(z.object({ prompt: z.string().trim().min(5).max(1000), options: z.array(z.string().trim().min(1).max(300)).min(2).max(6), answerIndex: z.number().int().min(0).max(5), explanation: z.string().trim().max(1500) })).min(1).max(200) });
const attemptInput = z.object({ answers: z.array(z.object({ questionId: z.string().min(1).max(80), selectedIndex: z.number().int().min(0).max(7).nullable() })).min(1).max(200) });

function publicLesson(data) { const { questions = [], ...lesson } = data; return { ...lesson, questions: questions.map(({ answerIndex, explanation, ...question }) => question) }; }
async function optionalUser(req) { const token = req.get('authorization')?.replace(/^Bearer\s+/i, ''); if (!token) return null; try { return await getAuth().verifyIdToken(token); } catch { return null; } }
async function adminOnly(req, res, next) { const user = await optionalUser(req); if (!user || user.email?.toLowerCase() !== adminEmail) return res.status(403).json({ error: 'هذه المنطقة مخصصة للإدارة.' }); req.user = user; next(); }
async function seedDemo() { const ref = store.collection('lessons').doc('clinical-foundations'); if ((await ref.get()).exists) return; await ref.set({ id: 'clinical-foundations', title: 'أساسيات التفكير السريري', module: 'Clinical Core', description: 'تجربة قصيرة للتعرّف على أسلوب Medcore.', level: 'تمهيدي', duration: 6, published: true, createdAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp(), questions: [{ id: 'q-1', prompt: 'ما الخطوة الأولى في التعامل مع مريض غير مستقر؟', options: ['جمع تاريخ مرضي مطوّل', 'تقييم ABCDE', 'طلب جميع التحاليل', 'كتابة التشخيص النهائي'], answerIndex: 1, explanation: 'تقييم مجرى الهواء والتنفس والدورة الدموية أولاً يحمي المريض من التأخير.' }, { id: 'q-2', prompt: 'أي اختيار يصف سؤالاً سريرياً جيداً؟', options: ['غامض ومفتوح بلا هدف', 'مرتبط بالمشكلة ويغيّر القرار', 'لا يرتبط بالفحص', 'يتكرر في كل حالة'], answerIndex: 1, explanation: 'السؤال الجيد يقرّبك من قرار سريري أو يستبعد احتمالاً مهماً.' }, { id: 'q-3', prompt: 'متى توثّق المعلومة المهمة؟', options: ['بعد نهاية اليوم', 'عند تذكّرها فقط', 'فور جمعها والتحقق منها', 'بعد خروج المريض'], answerIndex: 2, explanation: 'التوثيق المبكر والدقيق يقلل فقد المعلومات والأخطاء.' }] }); }

app.get('/api/config', (_req, res) => res.json({ firebase: { apiKey: process.env.FIREBASE_API_KEY, authDomain: process.env.FIREBASE_AUTH_DOMAIN, projectId: process.env.FIREBASE_PROJECT_ID, appId: process.env.FIREBASE_APP_ID } }));
app.get('/api/health', (_req, res) => res.json({ status: 'ok', service: 'medcore-api' }));
app.get('/api/lessons', async (_req, res, next) => { try { await seedDemo(); const snapshot = await store.collection('lessons').where('published', '==', true).get(); res.json(snapshot.docs.map(doc => { const { questions, ...lesson } = doc.data(); return lesson; })); } catch (error) { next(error); } });
app.get('/api/lessons/:id', async (req, res, next) => { try { await seedDemo(); const doc = await store.collection('lessons').doc(req.params.id).get(); if (!doc.exists || !doc.data().published) return res.status(404).json({ error: 'الدرس غير موجود.' }); res.json(publicLesson(doc.data())); } catch (error) { next(error); } });
app.post('/api/lessons/:id/attempts', async (req, res, next) => { try { const input = attemptInput.safeParse(req.body); if (!input.success) return res.status(400).json({ error: 'إجابات الاختبار غير صالحة.' }); const doc = await store.collection('lessons').doc(req.params.id).get(); if (!doc.exists || !doc.data().published) return res.status(404).json({ error: 'الدرس غير موجود.' }); const lesson = doc.data(); const answers = new Map(input.data.answers.map(answer => [answer.questionId, answer.selectedIndex])); const results = lesson.questions.map(question => ({ questionId: question.id, correct: answers.get(question.id) === question.answerIndex, answerIndex: question.answerIndex, explanation: question.explanation })); const score = results.filter(result => result.correct).length; const user = await optionalUser(req); if (user) await store.collection('users').doc(user.uid).collection('attempts').add({ lessonId: lesson.id, score, total: results.length, createdAt: FieldValue.serverTimestamp() }); res.json({ score, total: results.length, results, saved: Boolean(user) }); } catch (error) { next(error); } });
app.post('/api/feedback', async (req, res, next) => { try { const input = z.object({ message: z.string().trim().min(5).max(1000) }).safeParse(req.body); if (!input.success) return res.status(400).json({ error: 'اكتب رسالة بين 5 و1000 حرف.' }); const user = await optionalUser(req); await store.collection('feedback').add({ message: input.data.message, userId: user?.uid || null, createdAt: FieldValue.serverTimestamp(), status: 'new' }); res.status(201).json({ ok: true }); } catch (error) { next(error); } });
app.get('/api/me/attempts', async (req, res, next) => { try { const user = await optionalUser(req); if (!user) return res.status(401).json({ error: 'سجّل دخولك أولاً.' }); const rows = await store.collection('users').doc(user.uid).collection('attempts').orderBy('createdAt', 'desc').limit(50).get(); res.json(rows.docs.map(doc => ({ id: doc.id, ...doc.data() }))); } catch (error) { next(error); } });
app.get('/api/admin/lessons', adminOnly, async (_req, res, next) => { try { const snapshot = await store.collection('lessons').get(); res.json(snapshot.docs.map(doc => { const { questions, ...lesson } = doc.data(); return lesson; })); } catch (error) { next(error); } });
app.get('/api/admin/lessons/:id', adminOnly, async (req, res, next) => { try { const doc = await store.collection('lessons').doc(req.params.id).get(); doc.exists ? res.json(doc.data()) : res.status(404).json({ error: 'الدرس غير موجود.' }); } catch (error) { next(error); } });
app.post('/api/admin/lessons', adminOnly, async (req, res, next) => { try { const input = lessonInput.safeParse(req.body); if (!input.success || input.data.questions.some(question => question.answerIndex >= question.options.length)) return res.status(400).json({ error: 'بيانات الدرس غير صالحة.' }); const lesson = input.data; await store.collection('lessons').doc(lesson.id).set({ ...lesson, updatedAt: FieldValue.serverTimestamp(), createdAt: FieldValue.serverTimestamp() }, { merge: true }); res.status(201).json({ ok: true, id: lesson.id }); } catch (error) { next(error); } });
app.use((error, _req, res, _next) => { console.error(error); res.status(500).json({ error: 'حدث خطأ غير متوقع.' }); });
export default app;
